version: "3"
services:
  server:
    restart: always
    build: ./server
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    links:
      - mongo
  client:
    restart: always
    build: ./client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - server
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
