version: "3"
services:
  server:
    restart: always
    build: ./server
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    links:
      - mongo
  client:
    restart: always
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
  mongo:
    container_name: mongo
    image: 431949748449.dkr.ecr.us-west-2.amazonaws.com/parking-spot-finder:backend
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
