version: "3"
services:
  server-dev:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - ${PORT}:${PORT}
    links:
      - mongo
  client-dev:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - ./client:/usr/src/app/client
      - /client/node_modules
    ports:
      - "80:3000"
    depends_on:
      - server-dev
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
