version: "3"
services:
  backend:
    container_name: api
    restart: always
    build: ./backend
    ports:
      - "3001:3001"
    links:
      - mongo
    volumes:
      - ./backend:/usr/src/app/backend
  frontend:
    container_name: client
    restart: always
    build: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
    depends_on:
      - backend
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
